---
- name: Create postgresql user for mastodon
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present

- name: Create postgresql db for mastodon
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF-8
    lc_collate: ja_JP.UTF-8
    lc_ctype: ja_JP.UTF-8
    template: template0
    state: present
