---
authorized_key_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

nginx_mastodon_server_name: mstdn.naruh.com
nginx_mastodon_server_uses_https: "true"
ssl_certificate_path: "{{ lets_encrypt_config_dir }}/certificates/{{ lets_encrypt_domains[0] }}.crt"
ssl_certificate_key_path: "{{ lets_encrypt_config_dir }}/certificates/{{ lets_encrypt_domains[0] }}.key"

lets_encrypt_domains:
  - naruh.com
  - www.naruh.com
  - "{{ nginx_mastodon_server_name }}"
lets_encrypt_admin_email: hnakamur@gmail.com
lets_encrypt_config_dir: /etc/letsencrypt
lets_encrypt_lego_version: 0.3.1
lets_encrypt_tarball_url: https://github.com/xenolf/lego/releases/download/v{{ lets_encrypt_lego_version }}/lego_linux_amd64.tar.xz

mastodon_app_dir: /home/mastodon/live
mastodon_app_git_version: master
production_env_path: "{{ mastodon_app_dir }}/.env.production"

db_host: localhost
db_name: mastodon_production
db_user: mastodon
db_password: "{{ lookup('ini', 'db_password section=production file=passwords.ini') }}"
db_port: 5432

smtp_server: smtp.gmail.com
smtp_port: 587
smtp_login: hnakamur@gmail.com
smtp_password: "{{ lookup('ini', 'smtp_password section=production file=passwords.ini') }}"
smtp_from_address: hnakamur@gmail.com
smtp_delivery_method: smtp
smtp_auth_method: plain
smtp_openssl_verify_mode: none
smtp_enable_starttls_auto: "true"

redis_host: localhost
redis_port: 6379

mastodon_app_server_host: 127.0.0.1
mastodon_app_server_port: 3000

mastodon_streaming_host: localhost
mastodon_streaming_port: 4000

ntp_servers:
  # https://help.sakura.ad.jp/hc/ja/articles/206228721-NTP%E3%82%B5%E3%83%BC%E3%83%90%E3%81%AF%E7%94%A8%E6%84%8F%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%81%8B-
  - ntp1.sakura.ad.jp
  # http://wiki.nothing.sh/page/NTP/%BF%E4%BE%A9%B8%F8%B3%AB%A5%B5%A1%BC%A5%D0
  - ntp.jst.mfeed.ad.jp
  - ntp.nict.jp

iptables_worldwide_open_ports:
  - 22
  - 80
  - 443
