---
mastodon_app_dir: /home/mastodon/live
mastodon_app_git_version: master

production_env_path: "{{ mastodon_app_dir }}/.env.production"

redis_host: localhost
redis_port: 6379

db_host: localhost
db_name: mastodon_production
db_user: mastodon
db_password: "{{ lookup('ini', 'db_password section=production file=passwords.ini') }}"
db_port: 5432

local_domain: example.com
local_https: "false"

smtp_server: smtp.gmail.com
smtp_port: 587
smtp_login: hnakamur@gmail.com
smtp_password: "{{ lookup('ini', 'smtp_password section=production file=passwords.ini') }}"
smtp_from_address: hnakamur@gmail.com
smtp_delivery_method: smtp
smtp_auth_method: plain
smtp_openssl_verify_mode: none
smtp_enable_starttls_auto: "true"
