---
- name: Enable firewall logging
  ufw:
    logging: on

- name: Deny all incoming as default
  ufw:
    direction: incoming
    policy: deny
    log: yes

- name: Allow all outcoming as default
  ufw:
    direction: outgoing
    policy: allow

- name: Limit ssh
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow http
  ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow https
  ufw:
    rule: allow
    port: https
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled
