---
- name: Write iptables.conf
  template:
    src: iptables.rules.v4.j2
    dest: /etc/iptables/rules.v4
  register: firewall_iptables_rules_v4

- name: Run iptables-restore
  command: /usr/sbin/netfilter-persistent reload
  when: firewall_iptables_rules_v4.changed
