---
- name: Install bundler
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    gem install bundler
  args:
    chdir: "{{ mastodon_app_dir }}"
    creates: /home/mastodon/.rbenv/shims/bundle

# TODO: Make this task idempotent, but don't know how to check
- name: Install gems for mastodon
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bundle install
  args:
    chdir: "{{ mastodon_app_dir }}"
  tags:
    - bundle_install

# TODO: Make this task idempotent, but don't know how to check
- name: Install node modules for mastodon
  command: yarn install
  args:
    chdir: "{{ mastodon_app_dir }}"
  environment:
    PYTHON: "{{ ansible_python_interpreter }}"
  tags:
    - yarn_install

- include: config.yml
  tags:
    - config

# TODO: Make this task idempotent, but don't know how to check
- name: Migrate mastodon production db
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    RAILS_ENV=production bundle exec rails db:migrate
  args:
    chdir: "{{ mastodon_app_dir }}"
  tags:
    - migrate_db

# TODO: Make this task idempotent, but don't know how to check
- name: Precompile assets
  shell: |
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    bundle exec rails assets:precompile
  args:
    chdir: "{{ mastodon_app_dir }}"
  tags:
    - precompile_assets
