---
- name: Install dependency packages to build ruby
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git-core
    - g++
    - make
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libreadline-dev
    - imagemagick
