---
- include: dependencies.yml
  tags:
    - mastodon

- include: rbenv.yml
  become: yes
  become_user: mastodon
  tags:
    - mastodon

- include: ruby.yml
  become: yes
  become_user: mastodon
  tags:
    - mastodon

- include: build.yml
  become: yes
  become_user: mastodon
  tags:
    - mastodon

- include: web.yml
  tags:
    - mastodon
    - web

- include: sidekiq.yml
  tags:
    - mastodon
    - sidekiq

- include: streaming.yml
  tags:
    - mastodon
    - streaming
