---
- name: Create mastodon-web service
  template:
    src: mastodon-web.service.j2
    dest: /etc/systemd/system/mastodon-web.service

- name: Start and enable mastodon-web service
  systemd:
    name: mastodon-web
    state: started
    enabled: yes
    daemon_reload: yes
