---
- name: Disable ssh password login
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config_password_auth_ret

- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded
  when: sshd_config_password_auth_ret.changed
