---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - openssl
    - ca-certificates
    - vim
    - less
    - tar
    - gzip
    - xz-utils
